//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int id { get; set; }
        public int CharacterCustomizationId { get; set; }
        public int AccountId { get; set; }
        public int CharacterKlasseId { get; set; }
        public int Level { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Ras Ras { get; set; }
        public virtual CharacterInventory CharacterInventory { get; set; }
        public virtual CharacterKlasse CharacterKlasse { get; set; }
    }
}
