//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterCustomization
    {
        public int id { get; set; }
        public int RasId { get; set; }
        public string Gender { get; set; }
        public string Face { get; set; }
        public string HeadOption { get; set; }
        public string Marking { get; set; }
    
        public virtual Ras Ras { get; set; }
    }
}
