//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterSubklasse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharacterSubklasse()
        {
            this.GranaatSubklasses = new HashSet<GranaatSubklasse>();
            this.SubklasseAbilities = new HashSet<SubklasseAbility>();
            this.SubklassePerks = new HashSet<SubklassePerk>();
        }
    
        public int id { get; set; }
        public string Naam { get; set; }
        public int CharacterKlasseId { get; set; }
    
        public virtual CharacterKlasse CharacterKlasse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GranaatSubklasse> GranaatSubklasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubklasseAbility> SubklasseAbilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubklassePerk> SubklassePerks { get; set; }
    }
}
