//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyInventory
    {
        public int id { get; set; }
        public int CharacterInventoryId { get; set; }
        public int CurrencyId { get; set; }
        public int AmountOfCurrency { get; set; }
    
        public virtual CharacterInventory CharacterInventory { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
