//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DestinyEntities : DbContext
    {
        public DestinyEntities()
            : base("name=DestinyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Armor> Armor { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<CharacterCustomization> CharacterCustomization { get; set; }
        public virtual DbSet<CharacterInventory> CharacterInventory { get; set; }
        public virtual DbSet<CharacterKlasse> CharacterKlasse { get; set; }
        public virtual DbSet<CharacterSubklasse> CharacterSubklasse { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<CurrencyDropTable> CurrencyDropTable { get; set; }
        public virtual DbSet<CurrencyInventory> CurrencyInventory { get; set; }
        public virtual DbSet<Damagetype> Damagetype { get; set; }
        public virtual DbSet<Enemy> Enemy { get; set; }
        public virtual DbSet<GranaatAbilityDamage> GranaatAbilityDamage { get; set; }
        public virtual DbSet<GranaatSubklasse> GranaatSubklasse { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Locatie> Locatie { get; set; }
        public virtual DbSet<Map> Map { get; set; }
        public virtual DbSet<MapEnemy> MapEnemy { get; set; }
        public virtual DbSet<Mission> Mission { get; set; }
        public virtual DbSet<Npc> Npc { get; set; }
        public virtual DbSet<NpcSellItem> NpcSellItem { get; set; }
        public virtual DbSet<Perk> Perk { get; set; }
        public virtual DbSet<PerkArmor> PerkArmor { get; set; }
        public virtual DbSet<PerkWapen> PerkWapen { get; set; }
        public virtual DbSet<Ras> Ras { get; set; }
        public virtual DbSet<RewardTable> RewardTable { get; set; }
        public virtual DbSet<SpecialItem> SpecialItem { get; set; }
        public virtual DbSet<SpecialItemCategorie> SpecialItemCategorie { get; set; }
        public virtual DbSet<SubklasseAbility> SubklasseAbility { get; set; }
        public virtual DbSet<SubklassePerks> SubklassePerks { get; set; }
        public virtual DbSet<Wapen> Wapen { get; set; }
        public virtual DbSet<Wapenklasse> Wapenklasse { get; set; }
    }
}
