//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DestinyEntities : DbContext
    {
        public DestinyEntities()
            : base("name=DestinyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Armor> Armors { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<CharacterCustomization> CharacterCustomizations { get; set; }
        public virtual DbSet<CharacterKlasse> CharacterKlasses { get; set; }
        public virtual DbSet<CharacterSubklasse> CharacterSubklasses { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyDropTable> CurrencyDropTables { get; set; }
        public virtual DbSet<CurrencyInventory> CurrencyInventories { get; set; }
        public virtual DbSet<Damagetype> Damagetypes { get; set; }
        public virtual DbSet<Enemy> Enemies { get; set; }
        public virtual DbSet<GranaatAbilityDamage> GranaatAbilityDamages { get; set; }
        public virtual DbSet<GranaatSubklasse> GranaatSubklasses { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Locatie> Locaties { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<MapEnemy> MapEnemies { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Npc> Npcs { get; set; }
        public virtual DbSet<NpcSellItem> NpcSellItems { get; set; }
        public virtual DbSet<Perk> Perks { get; set; }
        public virtual DbSet<PerkArmor> PerkArmors { get; set; }
        public virtual DbSet<PerkWapen> PerkWapens { get; set; }
        public virtual DbSet<Ras> Ras1 { get; set; }
        public virtual DbSet<RewardTable> RewardTables { get; set; }
        public virtual DbSet<SpecialItem> SpecialItems { get; set; }
        public virtual DbSet<SpecialItemCategorie> SpecialItemCategories { get; set; }
        public virtual DbSet<SubklasseAbility> SubklasseAbilities { get; set; }
        public virtual DbSet<SubklassePerk> SubklassePerks { get; set; }
        public virtual DbSet<Wapen> Wapens { get; set; }
        public virtual DbSet<Wapenklasse> Wapenklasses { get; set; }
    }
}
