//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mission()
        {
            this.RewardTables = new HashSet<RewardTable>();
        }
    
        public int id { get; set; }
        public string Titel { get; set; }
        public string TaskDescr { get; set; }
        public string TypeBounty { get; set; }
        public Nullable<System.TimeSpan> RefreshTime { get; set; }
        public Nullable<System.TimeSpan> TimeToFinish { get; set; }
        public Nullable<System.TimeSpan> TimeBetweenEvents { get; set; }
        public Nullable<int> MinParticipants { get; set; }
        public string TypeMission { get; set; }
        public int LocatieId { get; set; }
        public Nullable<int> NpcId { get; set; }
    
        public virtual Locatie Locatie { get; set; }
        public virtual Npc Npc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RewardTable> RewardTables { get; set; }
    }
}
