//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Npc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Npc()
        {
            this.Mission = new HashSet<Mission>();
            this.NpcSellItem = new HashSet<NpcSellItem>();
        }
    
        public int id { get; set; }
        public string Type { get; set; }
        public bool IsMerchant { get; set; }
        public string Beschrijving { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public int MapId { get; set; }
        public int RasId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Map Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mission> Mission { get; set; }
        public virtual Ras Ras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NpcSellItem> NpcSellItem { get; set; }
    }
}
