//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerkArmor
    {
        public int id { get; set; }
        public int ArmorId { get; set; }
        public int PerkId { get; set; }
    
        public virtual Armor Armor { get; set; }
        public virtual Perk Perk { get; set; }
    }
}
