//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardTable
    {
        public int id { get; set; }
        public Nullable<int> MissionId { get; set; }
        public Nullable<int> EnemyId { get; set; }
        public int ItemId { get; set; }
        public int HoeveelheidItems { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Mission Mission { get; set; }
        public virtual Enemy Enemy { get; set; }
    }
}
