//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubklassePerk
    {
        public int id { get; set; }
        public string PerkName { get; set; }
        public string Effect { get; set; }
        public int CharacterSubklasseId { get; set; }
    
        public virtual CharacterSubklasse CharacterSubklasse { get; set; }
    }
}
