//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Destiny_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wapen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wapen()
        {
            this.Enemies = new HashSet<Enemy>();
            this.PerkWapens = new HashSet<PerkWapen>();
        }
    
        public int id { get; set; }
        public int Magazine { get; set; }
        public int FireRate { get; set; }
        public int Impact { get; set; }
        public int Stability { get; set; }
        public int ReloadSpeed { get; set; }
        public string Soort { get; set; }
        public int LightAmount { get; set; }
        public Nullable<int> MaxPerks { get; set; }
        public int DamagetypeId { get; set; }
        public int WapenklasseId { get; set; }
    
        public virtual Damagetype Damagetype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enemy> Enemies { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerkWapen> PerkWapens { get; set; }
        public virtual Wapenklasse Wapenklasse { get; set; }
    }
}
